package it.vu.mybatis.dao;

import java.util.List;
import it.vu.mybatis.model.ActivitiesStudents;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ActivitiesStudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTIVITIES_STUDENTS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    int insert(ActivitiesStudents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTIVITIES_STUDENTS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    List<ActivitiesStudents> selectAll();
}