package it.vu.mybatis.dao;

import java.util.List;
import it.vu.mybatis.model.Class;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    Class selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    List<Class> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CLASS
     *
     * @mbg.generated Thu May 04 19:32:59 EEST 2023
     */
    int updateByPrimaryKey(Class record);
}